#!/usr/bin/env bash

PHP="docker-compose run -T php php -d memory_limit=-1"
PHP_CS_FIXER="./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php"
PHPSTAN="./vendor/bin/phpstan analyse"
PSALM="./vendor/bin/psalm"
PHPUNIT="./bin/phpunit"
FILES=` git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | tr '\n' ' '`
if [ "$FILES" ]
then
  echo "php pre commit hook start"
  $PHP $PHP_CS_FIXER ${FILES}
  git add ${FILES}
  $PHP $PHPSTAN ${FILES}
  if [ $? -ne 0 ];
  then
    echo "phpstan analyse failed"
    exit 1;
  fi
  $PHP $PSALM ${FILES}
  if [ $? -ne 0 ];
  then
    echo "psalm analyse failed"
    exit 1;
  fi
  $PHP $PHPUNIT
  if [ $? -ne 0 ];
  then
    echo "unit test failed"
    exit 1;
  fi
  echo "php pre commit hook complete"
fi
