doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            media_file_id: 'App\Model\Media\Entity\DataType\IdType'
            media_image_info: 'App\Model\Media\Entity\DataType\ImageInfoType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Media:
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Media/Entity'
                prefix: 'App\Model\Media\Entity'
                alias: Media
