<?php

declare(strict_types=1);

namespace App\Media\Service\CacheStorage;

use App\Infrastructure\Middleware\AsyncWrapper\AsyncStamp;
use DomainException;
use League\Flysystem\Filesystem;
use League\Flysystem\FilesystemInterface;
use Symfony\Component\DependencyInjection\Attribute\Autoconfigure;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Lock\LockFactory;
use Symfony\Component\Lock\LockInterface;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Contracts\Service\Attribute\Required;

#[Autoconfigure(bind: [
    '$lockFactory'          => '@lockFactory',
    '$cacheStorageFolder'   => '%kernel.project_dir%/var/cache-storage',
    '$cacheStorageLifeTime' => '%env(CACHE_STORAGE_LIFE_TIME)%',
])]
class Storage extends Filesystem
{
    #[Required]
    public MessageBusInterface $bus;

    /**
     * @var \League\Flysystem\AdapterInterface
     */
    protected $adapter;

    /** @var Adapter */
    protected $adapterIpm;

    private int $lifeTime;

    public function __construct(
        string $cacheStorageFolder,
        private LockFactory $lockFactory,
        int $cacheStorageLifeTime = 30
    ) {
        $this->adapterIpm = new Adapter($cacheStorageFolder);
        parent::__construct($this->adapterIpm, null);
        $this->lifeTime = $cacheStorageLifeTime;
    }

    public function moveUploaded(File $file, string $path): File
    {
        $this->bus->dispatch(new Clean\Command($path), [new AsyncStamp($this->lifeTime)]);

        return $this->adapterIpm->moveUploaded($file, $path);
    }

    /**
     * @param string       $path
     * @param resource     $resource
     * @param array<mixed> $config
     */
    public function putStream($path, $resource, array $config = []): bool
    {
        $this->touch($path);

        return parent::putStream($path, $resource, $config); // TODO: Change the autogenerated stub
    }

    public function touch(string $path): string
    {
        $this->bus->dispatch(new Clean\Command($path), [new AsyncStamp($this->lifeTime)]);

        return $this->getRealPath($path);
    }

    public function getRealPath(string $path): string
    {
        return $this->adapterIpm->applyPathPrefix($path);
    }

    public function prepareDir(string $dir): void
    {
        $this->adapterIpm->prepareDir($dir);
    }

    /**
     * @param string       $path
     * @param string       $contents
     * @param array<mixed> $config
     */
    public function put($path, $contents, array $config = []): bool
    {
        $this->touch($path);

        return parent::put($path, $contents, $config);
    }

    /**
     * @param string       $path
     * @param string       $contents
     * @param array<mixed> $config
     */
    public function write($path, $contents, array $config = []): bool
    {
        $this->touch($path);

        return parent::write($path, $contents, $config);
    }

    public function hasDraft(string $path): bool
    {
        return $this->has($path.'-draft');
    }

    public function getDraft(string $path, FilesystemInterface $mainStorage): string
    {
        return $this->getLocalCopy($path, $mainStorage, true);
    }

    public function getLocalCopy(string $path, FilesystemInterface $mainStorage, bool $draft = false): string
    {
        $lock = $this->getLock($path);
        $lock->acquire(true);

        if ($this->has($path.($draft ? '-draft' : ''))) {
            return $this->getRealPath($path.($draft ? '-draft' : ''));
        }
        if (!$this->has($path)) {
            /** @var resource $stream */
            $stream = $mainStorage->readStream($path);
            $this->writeStream($path, $stream);
        }
        if ($draft) {
            if (!$this->has($path.'-draft')) {
                $this->copy($path, $path.'-draft');
            }
        }

        return $this->getRealPath($path.($draft ? '-draft' : ''));
    }

    public function getLock(string $path): LockInterface
    {
        return $this->lockFactory->createLock(static::class.'/'.$path, null);
    }

    /**
     * @param string       $path
     * @param resource     $resource
     * @param array<mixed> $config
     */
    public function writeStream($path, $resource, array $config = []): bool
    {
        $this->touch($path);

        return parent::writeStream($path, $resource, $config);
    }

    public function clean(string $path): void
    {
        $this->delete($path);
        $this->deleteDraft($path);
    }

    public function delete($path): bool
    {
        $this->getLock($path)->acquire(true);

        $deleted = $this->has($path) && parent::delete($path);
        if ($deleted) {
            while ('.' !== ($path = dirname($path))) {
                if (!$this->listContents($path)) {
                    $this->deleteDir($path);
                } else {
                    break;
                }
            }
        }

        return $deleted;
    }

    public function deleteDraft(string $path): bool
    {
        return $this->delete($path.'-draft');
    }

    /**
     * @param string $path
     *
     * @return resource
     *
     * @throws \League\Flysystem\FileNotFoundException
     */
    public function readStream($path)
    {
        return parent::readStream($path) ?: throw new DomainException("Can't open file.`{$path}`");
    }
}
